DROP DATABASE IF EXISTS 'click';

CREATE DATABASE 'click';

USE 'click';

CREATE TABLE IF NOT EXISTS 'click_counts' (
  'id' INT AUTO_INCREMENT PRIMARY KEY,
  'count' INT NOT NULL,
  'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);